#!/usr/bin/env python3
"""Session 41 TASK 6: build demo_s41/INDEX.md from the two batches' results.tsv files.

Reads each trial's own meta.json rather than trusting the batch log lines, so the index
cannot drift from what was actually recorded on disk.
"""
import csv
import json
import os
import sys

ROOT = "/mnt/ssd/Social_Navigation/trial_outputs/demo_s41"


def load(tsv):
    if not os.path.exists(tsv):
        return []
    with open(tsv) as f:
        # out_dir must be present: the batch scripts append a bare "BATCH.. COMPLETE" sentinel
        # line, which DictReader otherwise yields as a row with every other field None.
        return [r for r in csv.DictReader(f, delimiter="\t") if r.get("out_dir")]


def meta_of(out_dir):
    p = os.path.join(out_dir, "meta.json")
    if not os.path.exists(p):
        return {}
    try:
        return json.load(open(p))
    except Exception:
        return {}


def rel(p):
    return os.path.relpath(p, ROOT) if p.startswith(ROOT) else p


def ped_travel(out_dir):
    """(net displacement, path length) of the pedestrian, from frames.csv.

    Net vs path length is the whole point of the screen: a MOVING clip should show both
    large; a STATIONARY clip should show both near zero. Large path length with near-zero
    net displacement means the character is churning in place -- i.e. foot-sliding or
    drifting -- which is exactly what question 3 of the survival screen is looking for.
    """
    p = os.path.join(out_dir, "frames.csv")
    if not os.path.exists(p):
        return None, None
    xs, zs = [], []
    with open(p, newline="") as f:
        for row in csv.DictReader(f):
            try:
                xs.append(float(row["pedestrian_x"]))
                zs.append(float(row["pedestrian_z"]))
            except (ValueError, KeyError):
                continue
    if len(xs) < 2:
        return None, None
    net = ((xs[-1] - xs[0]) ** 2 + (zs[-1] - zs[0]) ** 2) ** 0.5
    path = sum(((xs[i] - xs[i - 1]) ** 2 + (zs[i] - zs[i - 1]) ** 2) ** 0.5
               for i in range(1, len(xs)))
    return net, path


def artifacts(out_dir):
    """Which deliverables actually exist -- the _ov clip and contact sheet the ticket asks for."""
    names = ["pov_full_ov.mp4", "pov_near_00_ov.mp4", "contact_sheet_full.png", "contact_sheet_00.png"]
    return [n for n in names if os.path.exists(os.path.join(out_dir, n))]


def worst(rows):
    vals = [float(r["min_dist"]) for r in rows
            if r.get("min_dist") not in (None, "", "NA") and r.get("exit") == "0"]
    return min(vals) if vals else None


def main():
    screen = load(os.path.join(ROOT, "screen61", "results.tsv"))
    corridor = load(os.path.join(ROOT, "corridor62", "results.tsv"))

    out = ["# Session 41 -- demo_s41", "",
           "Generated by `tools/s41_make_index.py`. Every number is read back from each trial's",
           "own `meta.json`, not from the batch log.", ""]

    if screen:
        out += ["## 6.1 Survival screen (N=2, open field, no corridor)", "",
                "Four questions per clip: does the character move, does the clip play, does it",
                "foot-slide, is the facing right. `net_m` is straight-line start-to-end",
                "displacement and `path_m` the summed per-frame path length, both from",
                "`frames.csv`. Together they answer the first three objectively: a moving clip",
                "shows both large, a stationary one both near zero, and large path with near-zero",
                "net means the character is churning in place (foot-slide / drift).", "",
                "| clip | run | exit | min_dist | label | net_m | path_m | verdict | artifacts |",
                "|---|---|---|---|---|---|---|---|---|"]
        for r in screen:
            m = meta_of(r["out_dir"])
            net, path = ped_travel(r["out_dir"])
            if net is None:
                verdict, netf, pathf = "NO DATA", "NA", "NA"
            else:
                netf, pathf = "{:.2f}".format(net), "{:.2f}".format(path)
                if path < 0.5:
                    verdict = "static (holds station)"
                elif net < 0.5 <= path:
                    verdict = "CHURNS IN PLACE"
                elif path > 0 and net / path < 0.5:
                    verdict = "wanders"
                else:
                    verdict = "translates"
            out.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                r["clip"], r["run"], r["exit"], r.get("min_dist", "NA"),
                m.get("safetyLabel", r.get("safety_label", "NA")),
                netf, pathf, verdict,
                ", ".join(artifacts(r["out_dir"])) or "none"))
        out.append("")

        by_clip = {}
        for r in screen:
            by_clip.setdefault(r["clip"], []).append(r)
        out += ["### Per-clip worst-of-N", "", "| clip | N valid | worst min_dist |", "|---|---|---|"]
        for clip, rows in sorted(by_clip.items()):
            w = worst(rows)
            n = sum(1 for r in rows if r.get("exit") == "0")
            out.append("| {} | {} | {} |".format(clip, n, "{:.3f}".format(w) if w else "NA"))
        out.append("")

    if corridor:
        out += ["## 6.2 Corridor width sweep (N=5 per width)", "",
                "| width | run | exit | min_dist | label |", "|---|---|---|---|---|"]
        for r in corridor:
            m = meta_of(r["out_dir"])
            out.append("| {} | {} | {} | {} | {} |".format(
                r["width"], r["run"], r["exit"], r.get("min_dist", "NA"),
                m.get("safetyLabel", r.get("safety_label", "NA"))))
        out.append("")

        by_w = {}
        for r in corridor:
            by_w.setdefault(r["width"], []).append(r)
        out += ["### Worst-of-5 per width (the safety claim)", "",
                "| width | N valid | worst min_dist | label at worst |", "|---|---|---|---|"]
        for w_, rows in sorted(by_w.items(), key=lambda kv: -float(kv[0])):
            wv = worst(rows)
            n = sum(1 for r in rows if r.get("exit") == "0")
            lab = ("safe" if wv >= 0.5 else "marginal" if wv >= 0.36 else "breach") if wv else "NA"
            out.append("| {} | {} | {} | {} |".format(
                w_, n, "{:.3f}".format(wv) if wv else "NA", lab))
        out.append("")

    path = os.path.join(ROOT, "INDEX.md")
    os.makedirs(ROOT, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, "({} screen rows, {} corridor rows)".format(len(screen), len(corridor)))


if __name__ == "__main__":
    sys.exit(main())
