#!/usr/bin/env python3
"""Session 43 TASK 6: build demo_s43/INDEX.md from the batch's own outputs.

Every number is read back from each trial's meta.json / states.csv / frames on disk rather than
from the batch log, so the index cannot drift from what was actually produced.

The "human eyeball" column is emitted as PENDING and is never auto-filled. Session 41's INDEX.md
listed all 18 screening runs as exit=0 / label=safe with no failure markers while the same
session's known_issues/ correctly failed 4 of 9 clips -- the file a human opens first contradicted
the file that had the answer. A column a machine cannot judge must say so rather than defaulting
to a pass.
"""
import csv
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s43_selfcheck  # noqa: E402

ROOT = "/mnt/ssd/Social_Navigation/trial_outputs/demo_s43"

HEADER = [
    "# Session 43 -- demo_s43",
    "",
    "> ## This batch is FORMAT VALIDATION, not a safety census.",
    "> **N = 1 per configuration.** The `min_dist` column is recorded because the pipeline emits it,",
    "> and it **must not be quoted as a safety result**. This project's standing rule is",
    "> worst-observed over N >= 5; a single sample cannot support any claim about worst-case",
    "> clearance, and `safety_label` on one run says nothing about the configuration.",
    ">",
    "> The purpose here is narrow: one trial of every shape, pushed through the new `video/` +",
    "> `vlm_eval/` output, so a human can watch the clips and confirm the format is right *before*",
    "> hundreds of trials are produced in it.",
    "",
    "Generated by `tools/s43_make_index.py`, reading each trial's own files on disk.",
    "",
]


def load_results(path):
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [r for r in csv.DictReader(f, delimiter="\t") if r.get("out_dir")]


def meta_of(d):
    p = os.path.join(d, "meta.json")
    if not os.path.exists(p):
        return {}
    try:
        return json.load(open(p))
    except Exception:
        return {}


def frame_counts(d):
    fd = os.path.join(d, "vlm_eval", "frames")
    if not os.path.isdir(fd):
        return 0, 0
    names = os.listdir(fd)
    regular = [n for n in names if re.fullmatch(r"frame_\d{4}\.png", n)]
    return len(regular), len(names) - len(regular)


def states_rows(d):
    p = os.path.join(d, "vlm_eval", "states.csv")
    if not os.path.exists(p):
        return [], []
    with open(p, newline="") as f:
        reader = csv.DictReader(f)
        return list(reader), reader.fieldnames or []


def ov_duration(d):
    p = os.path.join(d, "video", "pov_full_ov.mp4")
    if not os.path.exists(p):
        return None
    return s43_selfcheck.ffprobe_duration(p)


def main():
    rows = load_results(os.path.join(ROOT, "results.tsv"))
    if not rows:
        print("no results.tsv under", ROOT, file=sys.stderr)
        return 1

    out = list(HEADER)
    out += [
        "## Per-trial format check",
        "",
        "`overlay` is the pixel-level check from `tools/s43_selfcheck.py` check 3: the exported PNG",
        "is compared, inside the region `overlay.py` burns its telemetry into, against BOTH full",
        "videos. It must be much closer to the clean one than to the overlaid one. `checks` is how",
        "many of that tool's 8 checks passed.",
        "",
        "`eyeball` is for a human and is **never** filled in by this script. Watch",
        "`video/pov_full_ov.mp4` for each row and replace PENDING with pass/fail plus what you saw.",
        "",
        "| config | kind | exit | frames (reg+evt) | csv rows | event frames | overlay | checks | eyeball | min_dist (N=1, NOT a safety result) | notes |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]

    all_checks = []
    sample_dir = None
    for r in rows:
        d = r["out_dir"]
        m = meta_of(d)
        reg, evt = frame_counts(d)
        srows, _ = states_rows(d)
        events = sorted({e for row in srows for e in (row.get("event") or "").split("|") if e})
        res = s43_selfcheck.check_trial(d)
        all_checks.append((r["config"], res))
        by_n = {c["n"]: c for c in res["checks"]}
        n_ok = sum(1 for c in res["checks"] if c["ok"])
        notes = []
        if r.get("exit") not in ("0", 0):
            gates = (m.get("vlmEval") or {}).get("gateVerdicts") or {}
            failed = [k for k, v in gates.items() if v is False]
            notes.append("exit={} (gate: {}) -- vlm_eval still exported".format(
                r.get("exit"), ", ".join(failed) or "unknown"))
        if not events:
            notes.append("NO event frames")
        if m.get("velocitySource") in (None, "none"):
            notes.append("no velocity source")
        if srows and sample_dir is None and n_ok == 8:
            sample_dir = d

        out.append("| {} | {} | {} | {}+{} | {} | {} | {} | {}/8 | PENDING | {} | {} |".format(
            r["config"], r.get("kind", ""), r.get("exit", "?"), reg, evt, len(srows),
            ", ".join(events) or "**none**",
            "ok" if by_n.get(3, {}).get("ok") else "**FAIL**",
            n_ok,
            r.get("min_dist", "NA"),
            "; ".join(notes) or "-"))
    out.append("")

    failed = [(c, res) for c, res in all_checks if not res["pass"]]
    out += ["### Check failures", ""]
    if not failed:
        out.append("None -- all 8 checks passed on every trial.")
    else:
        for cfg, res in failed:
            for c in res["checks"]:
                if not c["ok"]:
                    out.append("- **{}** check {} ({}): {}".format(cfg, c["n"], c["name"], c["detail"]))
    out.append("")

    if sample_dir:
        out += ["## `states.csv` sample", "",
                "First 10 rows of `{}/vlm_eval/states.csv`. The first four columns are the agreed".format(
                    os.path.basename(sample_dir)),
                "interface, in the agreed order and capitalisation; everything after them is appended.",
                "Units, coordinate frames and the Unity/ROS sign convention are pinned in each trial's",
                "own `vlm_eval/README.md`.", "", "```"]
        with open(os.path.join(sample_dir, "vlm_eval", "states.csv")) as f:
            for i, line in enumerate(f):
                if i > 10:
                    break
                out.append(line.rstrip("\n"))
        out += ["```", ""]

    path = os.path.join(ROOT, "INDEX.md")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote {} ({} trials, {} with check failures)".format(path, len(rows), len(failed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
